#ifndef __PVR_CONFIG_H__
#define __PVR_CONFIG_H__

#include "cleanup.h"


/*** CONFIG SECTION ***/

#define CONFIG_BUILD_TYPE_RELEASE

/* #define CONFIG_SGX_EDM_TRACING */
/* #define CONFIG_SGX_MK_TRACE */
#define CONFIG_PVR_OMAP_DSS2
#define CONFIG_PVR_OMAP_USE_VSYNC
#define CONFIG_PVR_APM

/*** CONFIG SECTION ENDS ***/


#define LINUX
#define ANDROID

#define SGX530
#define SGX_CORE_REV 		121

#define DISPLAY_CONTROLLER	omaplfb

#define SUPPORT_SGX
#define SUPPORT_SGX530
#define SUPPORT_SGX_EVENT_OBJECT
#define SUPPORT_SGX_HWPERF
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING
#define SUPPORT_SRVINIT
#define SUPPORT_HW_RECOVERY
#define SUPPORT_PERCONTEXT_PB
#define SUPPORT_CPU_CACHED_BUFFERS
#define SUPPORT_CACHEFLUSH_ON_ALLOC
#define SUPPORT_MEMINFO_IDS
#define SUPPORT_OMAP3430_OMAPFB3
#define SUPPORT_LINUX_X86_WRITECOMBINE
#define SUPPORT_LINUX_X86_PAT
#define SUPPORT_ANDROID_PLATFORM

#define SYS_CUSTOM_POWERLOCK_WRAP
#define SYS_USING_INTERRUPTS
#define SYS_SGX_ACTIVE_POWER_LATENCY_MS	100

#define SGX_DYNAMIC_TIMING_INFO
#define SGX_EARLYSUSPEND

#define PVR_PROC_USE_SEQ_FILE
#define PVR_SECURE_HANDLES
#define PVR_SECURE_FD_EXPORT
#define PVR_LINUX_MISR_USING_WORKQUEUE

#define SERVICES4
#define TRANSFER_QUEUE
#define LDM_PLATFORM
#define PVR2D_VALIDATE_INPUT_PARAMS
#define PVR2D_ALT_2DHW


#ifdef CONFIG_PVR_APM
# define SUPPORT_ACTIVE_POWER_MANAGEMENT
#endif

#ifdef CONFIG_SGX_EDM_TRACING
# define PVRSRV_USSE_EDM_STATUS_DEBUG
#endif

#ifdef CONFIG_SGX_MK_TRACE
# define PVRSRV_DUMP_MK_TRACE
#endif

#if defined CONFIG_BUILD_TYPE_DEBUG
# define PVR_BUILD_TYPE "debug"
# define DEBUG
# define DEBUG_LINUX_MEMORY_ALLOCATIONS
# define DEBUG_LINUX_MEM_AREAS
# define DEBUG_LINUX_MMAP_AREAS
# define DEBUG_BRIDGE_KM
# define DLL_METRIC 1

#elif defined CONFIG_BUILD_TYPE_RELEASE
# define PVR_BUILD_TYPE  "release"
# define RELEASE
#endif


#ifndef __linux__
# define __linux__
#endif

#ifndef LINUX
# define LINUX
#endif

#ifndef _XOPEN_SOURCE
# define _XOPEN_SOURCE  600
#endif

#endif /* __CONFIG_H__ */
